app = "9router-deploy"
primary_region = "sin"

[build]

[http_service]
  internal_port = 20128
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "9router_data"
  destination = "/app/data"
